export const config = {
  FINFY_API: process.env.NEXT_PUBLIC_FINFY_API,
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  STRAPI_PLAN_LINK: process.env.NEXT_PUBLIC_STRAPI_PLAN_LINK,
  STRAPI_MONTHLY_ID: process.env.NEXT_PUBLIC_STRAPI_MONTHLY_ID,
  STRAPI_YEARLY_ID: process.env.NEXT_PUBLIC_STRAPI_YEARLY_ID,
  STRAPI_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRAPI_MONTHLY_PRICE_ID,
  STRAPI_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRAPI_YEARLY_PRICE_ID,
} as const;
